[build-system]
requires = ["setuptools>=64", "wheel", "torch>=2.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "emm"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "numpy>=1.26.0",
]
requires-python = ">=3.9,<3.12"

[tool.setuptools]
packages = ["emm"]
